### ISSUE TITLE
MovieLister original example

### ISSUE THREAD

**Issue by rmk135** [mzipay/Aglyph#1]
Hello Matthew,

Is this https://github.com/mzipay/Aglyph/tree/master/example/movielisterapp-aglyph/movies reworked version of https://github.com/ets-labs/python-dependency-injector/tree/master/examples/miniapps/movie_lister/movies ?

I see that your thing was pushed like 2 years ago, but I'm curious that it is mostly the same thing (idea) that I got (and implemented) a month ago.

So, can you, please, proof or disproof that you used example from my docs as an origin for yours?

**Comment by mzipay** [comment]
Hi rmk135,

No, the Aglyph movielisterapp is not based on your example. Aglyph movielisterapp is based on the conceptual app described in Martin Fowler's "Inversion of Control Containers and the Dependency Injection pattern" article (see the "A Naive Example" section at http://martinfowler.com/articles/injection.html, also linked to from Aglyph's "getting started" documentation page).

As you noted, Aglyph's movielisterapp was last _modified_ over two years ago; however, it was actually _written_ about five years ago, on 2011-08-30, with the 1.0.0 release (reference doc/build/html/get-started.html from the distributions available at https://sourceforge.net/projects/aglyph/files/aglyph/1.0.0/), and was first physically packaged with the release distributions on 2013-03-21 with release 1.1.1. (https://sourceforge.net/projects/aglyph/files/aglyph/1.1.1/).

**Comment by rmk135** [comment]
Thanks! It's absolutely amazing :)

I mean that I also used the same Martin Fowler's article (http://martinfowler.com/articles/injection.html) as an original idea for this example: https://github.com/ets-labs/python-dependency-injector/tree/master/examples/miniapps/movie_lister

It's absolutely amazing that we, working completely independently, found very similar design solutions (for example putting container in ``movies/__init__.py``).

I'm incredibly impressed!

Thanks a lot for your answer,
Have a nice day,
Roman

**Comment by mzipay** [comment]
Thanks, Roman. Yes, it's a pretty cool coincidence. It's really intriguing that, using the same source of inspiration, we devised very similar examples but yet very different implementations library-wise. Good luck to you!

**Comment by rmk135** [comment]
U 2, Matthew! ;)
