### ISSUE TITLE
http://ninthtest.net url no longer points anywhere sensible

### ISSUE THREAD

**Issue by tim-mitchell** [mzipay/Aglyph#6]
In several places you mention http://ninthtest.net/aglyph-python-dependency-injection/ as the home-page but this url resolves to random advertising.

**Comment by mzipay** [comment]
My domain expired and got hijacked. It is now ninthtest.info, but some of
my project documentation has not been updated yet.

**Comment by mzipay** [comment]
See http://ninthtest.info/aglyph-python-dependency-injection/
or
http://aglyph.readthedocs.io/en/latest/

**Comment by mzipay** [comment]
Updated all references in the master branch.
