### ISSUE TITLE
List of references

### ISSUE THREAD

**Issue by dhoomakethu** [mzipay/Aglyph#7]
Hi,

I am trying to pass references of the components as a list argument to my constructor with out any success. As a workaround I am passing the list as list of strings and retrieving the the relevant objects from the context. Is there a better way to do this ?

 Here is my pseudo xml config I am trying to use

```
<component id="dummy" dotted-name="dummy.component">
<init>
       <arg> name="dependencies">
              <list>
                     <reference>reference1</reference>
                     <reference>reference2</reference>
              </list>
      </arg>
</init>
</component>
```

P.S: I can also pass individual component reference as arguments.

**Comment by mzipay** [comment]
@dhoomakethu You almost have it.  What you are trying to do is absolutely possible, but there is a syntax error in the XML you posted (`<arg> name="dependencies">` is not well-formed XML) and a slight misuse of the `<reference>` element, which is an empty element that expects an ``id`` attribute.

Here is what your "dummy" component should look like:

```xml
    <component id="dummy" dotted-name="dummy.component">
        <init>
            <arg name="dependencies">
                <list>
                    <reference id="reference1" />
                    <reference id="reference2" />
                </list>
            </arg>
        </init>
    </component>
```

Give this a try and let me know how it works out - it should resolve your issue.

**Comment by dhoomakethu** [comment]
Perfect, Thanks!!!

**Comment by mzipay** [comment]
You're welcome. Please do let me know if you encounter any other issues.
